"""Toolbox plugins: luma_engine extensions the agent (or a user) wrote — effects, templates,
audio instruments and QC checks — discovered at runtime from the toolbox:

    from luma_engine.plugins import liquid_chrome_sweep
    liquid_chrome_sweep.apply(frame, t, ...)

Discovery: every directory in ``LUMA_PLUGIN_DIRS`` (``:``-separated; Luma Studio sets it to
``/data/toolbox/plugins``) may hold ``registry.json`` — ``{name: {kind, version, enabled}}``,
written by the studio once a plugin's tests pass — and one sub-directory per plugin with
``plugin.yaml`` and ``__init__.py``.  Only *enabled* plugins import (``LUMA_PLUGIN_TESTING=name``
lets a plugin's own tests import it before it is enabled).  Without a registry file every
plugin directory is considered enabled (handy for local development).

Kinds and their conventions:
* ``fx``         — functions drawing into a :class:`~luma_engine.layers.Frame` (e.g. ``apply(frame, t, **params)``);
* ``template``   — a parameterised scene: ``build(**params) -> Scene`` (generated by ``template_save``);
* ``instrument`` — audio synthesis, e.g. ``synth(duration, sr=48000, **params) -> np.ndarray``;
* ``qc_check``   — ``check(video_path, info) -> {name, pass, value, expected, detail, severity}``,
  run automatically by :func:`luma_engine.qc.qc_report`.
"""
from __future__ import annotations

import importlib.util
import json
import os
import sys
from pathlib import Path

KINDS = ("fx", "template", "instrument", "qc_check")


def plugin_dirs() -> list[Path]:
    raw = os.environ.get("LUMA_PLUGIN_DIRS", "/data/toolbox/plugins")
    return [Path(p) for p in raw.split(":") if p]


def _meta(d: Path) -> dict:
    try:
        import yaml

        return yaml.safe_load((d / "plugin.yaml").read_text()) or {}
    except Exception:  # noqa: BLE001
        return {}


def registry() -> dict[str, dict]:
    """name → {kind, version, enabled, dir}."""
    out: dict[str, dict] = {}
    testing = os.environ.get("LUMA_PLUGIN_TESTING", "")
    for root in plugin_dirs():
        if not root.is_dir():
            continue
        reg_file = root / "registry.json"
        reg = None
        if reg_file.exists():
            try:
                reg = json.loads(reg_file.read_text())
            except ValueError:
                reg = {}
        for d in sorted(root.iterdir()):
            if not (d / "plugin.yaml").exists() or d.name in out:
                continue
            if reg is not None:
                info = reg.get(d.name)
                enabled = bool(info and info.get("enabled"))
            else:
                info, enabled = None, True
            m = _meta(d)
            out[d.name] = {"name": d.name, "kind": (info or {}).get("kind") or m.get("kind", "fx"), "version": (info or {}).get("version") or m.get("version"),
                           "description": m.get("description", ""), "enabled": enabled or d.name == testing, "dir": str(d)}
    return out


def list_plugins(kind: str | None = None, include_disabled: bool = False) -> list[dict]:
    return [p for p in registry().values() if (include_disabled or p["enabled"]) and (kind is None or p["kind"] == kind)]


def _spec(name: str):
    info = registry().get(name)
    if info is None:
        raise ModuleNotFoundError(f"no toolbox plugin named {name!r} (looked in {', '.join(map(str, plugin_dirs()))})", name=f"{__name__}.{name}")
    if not info["enabled"]:
        raise ImportError(f"toolbox plugin {name!r} is disabled (its tests have not passed, or it was switched off in the Toolbox)")
    d = Path(info["dir"])
    spec = importlib.util.spec_from_file_location(f"{__name__}.{name}", d / "__init__.py", submodule_search_locations=[str(d)])
    if spec is None or spec.loader is None:
        raise ImportError(f"plugin {name!r} has no __init__.py")
    return spec, info


class _Finder:
    """``import luma_engine.plugins.<name>`` / ``from luma_engine.plugins import <name>``."""

    @staticmethod
    def find_spec(fullname, path=None, target=None):
        prefix = __name__ + "."
        if not fullname.startswith(prefix) or "." in fullname[len(prefix):]:
            return None
        spec, _ = _spec(fullname[len(prefix):])
        return spec


if not any(isinstance(f, _Finder) for f in sys.meta_path):
    sys.meta_path.insert(0, _Finder())


def load(name: str):
    """Import a plugin as ``luma_engine.plugins.<name>``."""
    import importlib

    mod = importlib.import_module(f"{__name__}.{name}")
    mod.PLUGIN = registry().get(name)
    return mod


def __getattr__(name: str):
    if name.startswith("__"):
        raise AttributeError(name)
    try:
        return load(name)
    except ImportError as e:
        raise AttributeError(str(e)) from None


def template_builder(init_file: str):
    """``build(**params)`` for a template plugin: its ``scene.py`` loaded with plugin.yaml defaults + params
    (scene attributes such as logo, background, wordmark, font, timings; width/height/fps/duration)."""
    d = Path(init_file).resolve().parent

    def build(**params):
        from ..render import load_scene

        meta = _meta(d)
        defaults = {k: v.get("default") for k, v in ((meta.get("params") or {}).get("properties") or {}).items() if "default" in v}
        args = {**defaults, **{k: v for k, v in params.items() if v is not None}}
        return load_scene(str(d / "scene.py"), **args)

    build.__doc__ = f"Build the {d.name} template scene (params: see plugin.yaml)."
    return build
